name: Linter as style guide

# **What it does**: Lints only files modified in a PR. Posts an annotation on lines with errors.
# **Why we have it**: To make it easy to review PRs
# **Who does it impact**: Open source contributors making changes to .md files

on: [pull_request]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      # - name: Setup node
      #   uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
      #   with:
      #     node-version: 16.14.x
      #     cache: npm

      # - name: Install dependencies
      #   run: npm ci

      # Create a Liquid-free version of each Markdown file. This versions aren't
      # stored anywhere and will be torn down along with the checkout after each run.
      # NOTE: This hack only works because the step that removes Liquid does NOT
      # change line breaks in the files.
      - name: Remove Liquid
        # run: .github/action-scripts/remove-liquid.js
        run: sed -e -r -i 's/{%.*%}//g' content/* data/*

      - name: Vale (fork)
        uses: errata-ai/vale-action@cb5ab4acdaf3169b1b5e5b4785d844aaea6366a0
        with:
          debug: true
          files: __onlyModified
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
